{% set python_min = '3.11.*' %}
{% set python_max = '3.14.*' %}
{% set name = "mosdef-gomc" %}
{% set version = "1.6.0" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GOMC-WSU/MoSDeF-GOMC/archive/{{ version }}.tar.gz
  sha256: 389e46cf471b7b7b589b280ca5ecaca7a3bc8aa5777fd3764901ea35c0285f7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: {{ build_number }}

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - netcdf4
    - garnett
    - gsd =3.3.2
    - pycifrw
    - sympy
    - symengine
    - python-symengine
    - numpy >=2.0,<2.3
    - forcefield-utilities >=0.4.0
    - foyer >=1.0.1
    - gmso >=0.12.4
    - mbuild >=1.2.1
    - pytest
    - pytest-cov
    - coverage

test:
  imports:
    - mosdef_gomc
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/GOMC-WSU/MoSDeF-GOMC
  summary: A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  description: |
    A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://github.com/GOMC-WSU/MoSDeF-GOMC
  dev_url: https://github.com/GOMC-WSU/MoSDeF-GOMC

extra:
  recipe-maintainers:
    - umesh-timalsina
    - bc118
