{% set name = "mosdef-gomc" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GOMC-WSU/MoSDeF-GOMC/archive/{{ version }}.tar.gz
  sha256: 19b3536eb8895826ceb483cdf0859266ab358d2c01d7f877f8ec87d284c2cd5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - foyer
    - mbuild >=0.14.2

test:
  imports:
    - mosdef_gomc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/GOMC-WSU/MoSDeF-GOMC
  summary: A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  description: |
    A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/GOMC-WSU/MoSDeF-GOMC
  dev_url: https://github.com/GOMC-WSU/MoSDeF-GOMC

extra:
  recipe-maintainers:
    - umesh-timalsina
    - bc118
