{% set python_min = '3.10' %}
{% set python_max = '3.12' %}
{% set name = "mosdef-gomc" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GOMC-WSU/MoSDeF-GOMC/archive/{{ version }}.tar.gz
  sha256: cb5576c236905df0499304891ee82e7a5bfa836c9834f3592138fa5797980e78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - garnett
    - gsd
    - pycifrw
    - sympy
    - symengine
    - python-symengine
    - forcefield-utilities >=0.3.0
    - foyer >=1.0.0
    - gmso >=0.12.4
    - mbuild >=1.1.0
    - pytest
    - pytest-cov
    - coverage

test:
  imports:
    - mosdef_gomc
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/GOMC-WSU/MoSDeF-GOMC
  summary: A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  description: |
    A User-Friendly Python Interface for Creating All of the files required to run a GPU Optimized Monte Carlo (GOMC) simulation engine via the Molecular Simulation Design Framework (MoSDeF) software.
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  doc_url: https://github.com/GOMC-WSU/MoSDeF-GOMC
  dev_url: https://github.com/GOMC-WSU/MoSDeF-GOMC

extra:
  recipe-maintainers:
    - umesh-timalsina
    - bc118
